name: Build
on: [push]

jobs:
  ci:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Decrypt the dataset
        run: |
          echo "$KEY" > pass.txt
          gpg --batch --passphrase-file pass.txt --output generator/registrations.csv --decrypt generator/registrations.csv.gpg
        env:
          KEY: ${{ secrets.KEY }}

      - name: Build report
        run: pnpm run build

      - name: Deploy report to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
